### ISSUE TITLE
Possible JSON encoding quote issue

### ISSUE THREAD

**Issue by jabelk** [kecorbin/nso-netdevops-demo#1]
running ansible devel 
http://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#running-from-source

root@LINUXHOST:~/ansiblensotest/nso-netdevops-demo# ansible --version
ansible 2.6.0 (devel dc09ddfbd5) last updated 2018/04/18 17:41:05 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansiblensotest/ansible/lib/ansible
  executable location = /root/ansiblensotest/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
root@LINUXHOST:~/ansiblensotest/nso-netdevops-demo#

root@LINUXHOST:~/ansiblensotest/nso-netdevops-demo# ncs --version
4.5.3
root@LINUXHOST:~/ansiblensotest/nso-netdevops-demo#

```
root@LINUXHOST:~/ansiblensotest/nso-netdevops-demo# python generate_ansible.py
Syncing Configuration from Devices
[u'devnet_nxos_sandbox_device', u'itdelab-wl-wlc2', u'netsim-aireos-0', u'netsim-aireos-1', u'netsim-asa-0', u'netsim-asa-1', u'netsim-ios-0', u'netsim-ios-1', u'netsim-nx-0', u'netsim-nx-1', u'rtp5-itnlab-dt-gw1', u'rtp5-itnlab-dt-sw1', u'svl-cat3850-sw1', u'svl-isr4451-gw1']
Generating host_vars for devnet_nxos_sandbox_device
Generating host_vars for itdelab-wl-wlc2
Generating host_vars for netsim-aireos-0
Generating host_vars for netsim-aireos-1
Generating host_vars for netsim-asa-0
Generating host_vars for netsim-asa-1
Generating host_vars for netsim-ios-0
Generating host_vars for netsim-ios-1
Generating host_vars for netsim-nx-0
Generating host_vars for netsim-nx-1
Generating host_vars for rtp5-itnlab-dt-gw1
Generating host_vars for rtp5-itnlab-dt-sw1
Generating host_vars for svl-cat3850-sw1
Traceback (most recent call last):
  File "generate_ansible.py", line 51, in <module>
    main()
  File "generate_ansible.py", line 43, in main
    config['config'] = nso.get_device_config(d)['tailf-ncs:config']
  File "/root/ansiblensotest/nso-netdevops-demo/helpers/nso.py", line 79, in get_device_config
    return self._utf8_encode(resp.json())
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 101 column 17 (char 2412)
root@LINUXHOST:~/ansiblensotest/nso-netdevops-demo#
```

It is generating the files, so json-rpc is working, but I am thinking something on that 3850 lab switch config is breaking the JSON-YAML conversion.

**Comment by kecorbin** [comment]
it seems that the REST API is sending out bad JSON.  I was able to recreate this in netsim.  the following config

**Comment by jabelk** [comment]
opened a ticket with NED team to fix. Issue not related to this library, but parsing bug on cisco-ios NED.
